package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"smolf-main/gql"
)

// Login is the resolver for the Login field.
func (r *queryResolver) Login(ctx context.Context, payload gql.LoginPayload) (*gql.AuthResponse, error) {
	return r.Auth.HandleLogin(ctx, payload)
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
