// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type AuthResponse struct {
	UserID int    `json:"user_id"`
	Token  string `json:"token"`
}

type LoginPayload struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterPayload struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}
